export const LOGIN_USER = "LOGIN_USER"
export const USERS_ERROR = "USER_ERROR"
export const ERROR = "ERROR"
export const REMOVE_ERROR = "REMOVE_ERROR"
export const REGISTER_REQUEST = "REGISTER_REQUEST"
